# YOUR NAME OR TITLE OF YOUR SITE
name: Monkey Maniu

# YOUR BRAND/PERSONAL TAGLINE
tagline: 'Gamer, music and tech enthusiast, Loves pineapple on pizza and unicorns.(he/him)' 

# YOUR/BRAND IMAGE URL
Image_URL: https://monkey.maniu.eu/image/profile.jpeg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
#Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Mastodon
    URL: https://mstdn.io
    Username: '@monkey_maniu'
    Color: '#3b5998'
    Icon-Class: fab fa-mastodon

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: monkey_maniu
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: 
    Username: 
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter
    
    # THREADS.NET
  - Name: Threads
    URL: https://threads.net/
    Username: monkey_maniu
    Color: '#f1c40f'
    Icon-Class: fa-solid fa-at
    Text_Color: '#ffffff'  

    # CLUBHOUSE
  - Name: Clubhouse
    URL: https://clubhouse.com
    Username: '@monkey_maniu'
    Color: '#f1c40f'
    Icon-Class: fas fa-hand-paper -mt-0.5
    
    # LINKEDIN
  - Name: MeWe
    URL: https://mewe.com/
    Username: monkey_maniu.82
    Color: '#2867B2'
    Icon-Class: fab fa-facebook

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/
    Username: '@monkey_maniu'
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: 
    Username: 
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:monkey2maniu@gmail.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # TWITCH
  - Name: Twitch
    URL: 'https://twitch.tv'
    Username: monkey_maniu
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

    # VIMEO
  - Name: Vimeo
    URL: 'https://vimeo.com'
    Username: monkey2maniu
    Icon-Class: fab fa-vimeo-v
    Color: '#1ab7ea'
    Text_Color: '#ffffff'

    # MESSENGER
  - Name: Messenger
    URL: https://facebook.com
    Username: '@maniumonkey'
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

    # REDDIT
  - Name: Reddit
    URL: http://reddit.com/u
    Username: monkey_maniu
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: 
  #   Username: 
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

    # TELEGRAM
  - Name: Telegram
    URL: 
    Username: 
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # SNAPCHAT
  - Name: Snapchat
    URL: 
    Username: 
    Color: '#FFFC00'
    Text_Color: '#000000'
    Icon-Class: fab fa-snapchat-ghost

    # STEAM
  - Name: Steam
    URL: 
    Username: 
    Color: '#66c0f4'
    Text_Color: '#000000'
    Icon-Class: fab fa-steam

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

    # PINTEREST
  - Name: Pinterest
    URL: https://pinterest.com
    Username: 'monkey_maniu'
    Color: '#E60023'
    Icon-Class: fab fa-pinterest

    # BEHANCE
  - Name: Behance
    URL: 
    Username: 
    Color: '#1769ff'
    Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    # DEVIANTART
  - Name: DeviantArt
    URL: 
    Username: 
    Icon-Class: fab fa-deviantart
    Color: '#05CC46'
    Text_Color: '#ffffff'

    # FIGMA
  - Name: Figma
    URL: 
    Username: ''
    Icon-Class: fab fa-figma
    Color: '#ff2865'
    Text_Color: '#ffffff'

    # SPOTIFY
  - Name: Spotify
    URL: 
    Username: 
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

    # SOUNDCLOUD
  - Name: SoundCloud
    URL: 
    Username: 
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud

  #    # TIKTOK
#  -  Name: TikTok
#     URL: https://www.tiktok.com
#     Username: monkey_maniu
#     Color: '#FE2C55'
 #    Icon-Class: fab fa-tiktok

    # MEDIUM
  - Name: Medium
    URL: 
    Username: 
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'

    # DEV.TO
  - Name: Dev.to
    URL: 
    Username: 
    Icon-Class: fab fa-dev
    Color: '#ffffff'
    Text_Color: '#000000'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: 
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

  # BUY ME A COFFEE
  - Name: BuyMeACoffee
    URL: 
    Username: 
    Icon-Class: fas fa-mug-hot
    Color: '#FFDD00'
    Text_Color: '#000000'

    # CUSTOM LINK
  - Name: Blog
    URL: https://journal.maniu.eu/
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

  - Name: Links
    URL: 
    Icon-Class: fas fa-link
    Color: '#d94869'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

include: [ "/.well-known" ]
# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
